old_django_test_tasks/old_django_test_tasks/apps/blog/urls.py
from django.urls import path

from . import views

app_name = 'blog'


urlpatterns = [
    path('', views.PostList.as_view(), name='home'),
    path('add/', views.PostCreate.as_view(), name='add_post'),
    path('<slug:slug>/', views.PostDetail.as_view(), name='post_detail'),
]

old_django_test_tasks/old_django_test_tasks/tests_django/urls.py
from django.conf import settings
from django.urls import include, path
from django.conf.urls import url
from django.contrib import admin
from django.contrib.staticfiles.urls import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^o/', include('oauth2_provider.urls', namespace='oauth2_provider')),
    path('cats/', include('apps.cats.urls')),
    path('cars/', include('apps.cars.urls')),
    # path('image-sizer/', include('apps.image_sizer.urls')),
    path('loans/', include('apps.loans.urls')),
    path('menu-tag/', include('apps.menu_tag.urls')),
    path('playschool/', include('apps.playschool.urls')),
    # path('testing/', include('apps.testing.urls')),
    path('transfer-money/', include('apps.transfer_money.urls')),
    path('generate-keys/', include('apps.gen_keys.urls')),
    path('blog/', include('apps.blog.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls'))
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


if settings.DEBUG:
    urlpatterns += static(
        settings.STATIC_URL, document_root=settings.STATIC_ROOT
    )
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

old_django_test_tasks/old_django_test_tasks/apps/blog/models.py
from django.db import models
from django.urls import reverse
from slugify import slugify


from ckeditor.fields import RichTextField


class Post(models.Model):
    title = models.CharField(max_length=200, unique=True)
    slug = models.SlugField(max_length=200, unique=True)
    created_on = models.DateTimeField(auto_now_add=True)
    content = RichTextField()
    image = models.ImageField(upload_to=f'blog/images/%Y/%m/%d')

    class Meta:
        ordering = ['-created_on']

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('blog:post_detail', args=[self.slug])

old_django_test_tasks/old_django_test_tasks/apps/blog/forms.py
from django import forms

from ckeditor.widgets import CKEditorWidget

from .models import Post


class PostCreateForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('title', 'content', 'image')
        widgets = {
            'title': forms.TextInput(
                attrs={
                    'class': 'title-field',
                    'placeholder': 'Введите название статьи'
                }
            ),
            'content': CKEditorWidget(attrs={'class': 'content-field'}),
            'image': forms.ClearableFileInput(attrs={'class': 'image-field'}),
        }

old_django_test_tasks/old_django_test_tasks/apps/blog/views.py
from django.views.generic import ListView, DetailView
from django.views.generic.edit import CreateView

from .models import Post
from .forms import PostCreateForm


class PostList(ListView):
    queryset = Post.objects.all().order_by('-created_on')[:10]
    template_name = 'index.html'


class PostDetail(DetailView):
    model = Post
    template_name = 'post_detail.html'


class PostCreate(CreateView):
    model = Post
    form_class = PostCreateForm
    template_name = 'post_create.html'

old_django_test_tasks/old_django_test_tasks/apps/blog/templates/base.html
<!DOCTYPE html>
<html>
    <head>
        <title>Блог Kodland</title>
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
    </head>

    <body>
        {% block content %}
        {% endblock content %}
        <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
    </body>
</html>

old_django_test_tasks/old_django_test_tasks/apps/blog/templates/index.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<link rel="stylesheet" href="{% static 'blog/css/main.css' %}">
<div class="container">
    <div class="row">
        {% include 'includes/header.html' %}
    </div>
    <hr>

    <div class="row">
        {% include 'includes/heading-article.html' %}
    </div>
    <hr>

    <div class="row">
        <h3 class="articles-list-header">Другие статьи</h3>
        <ul class="articles-list">
            {% for post in post_list|slice:"1:" %}
              <li class="articles-list-article">
                  <a href="{% url 'blog:post_detail' post.slug  %}">
                      <p class="articles-list-article-created">{{ post.created_on}} </p>
                      <div class="articles-list-article-image-container">
                        <img class="articles-list-article-image" src="{{ post.image.url }}">
                      </div>
                      <h4 class="articles-list-article-header">{{ post.title }}</h4>
                  </a>
              </li>
            {% endfor %}
        </ul>
    </div>
</div>

{%endblock%}

old_django_test_tasks/old_django_test_tasks/apps/blog/templates/post_create.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<link rel="stylesheet" href="{% static 'blog/css/main.css' %}">
<div class="container">
    <div class="row">
        {% include 'includes/header.html' %}
    </div>
    <div class="row">
      <h2 class="article-create-header">Добавить статью</h2>
      <form action='' method='post' enctype='multipart/form-data'>
        {% csrf_token %}
        {{ form.media }}

        <div class="form-first-row">
          <input type="text" name="title" class="title-field" placeholder="Введите название статьи" maxlength="200" required="" id="id_title">
          <button class='publish-button' type='submit'>Опубликовать</button>
        </div>
        <div class="form-second-row">
          <div class="cke-input">{{ form.visible_fields.1}}</div>
          <div class="image-button">
            <input type="file" name="image" class="image-field" accept="image/*" required="" id="id_image"/>
            <label class="image-upload-container" for="id_image">
              <div class="image-upload-message">Загрузить изображение</div>
              <div class="image-upload-button">Файл</div>
            </label>
          </div>
        </div>
<!--        {% for field in form.visible_fields %}-->
<!--          {{ field }}-->
<!--        {% endfor %}-->
<!--        {{ form.as_p }}-->
      </form>
    </div>
</div>
{% endblock %}

old_django_test_tasks/old_django_test_tasks/apps/blog/templates/post_detail.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<link rel="stylesheet" href="{% static 'blog/css/main.css' %}">
<div class="container">
    <div class="row">
        {% include 'includes/header.html' %}
    </div>

    <h2 class="article-header">{{ post.title }}</h2>
    <img src="{{ post.image.url }}">
    <div>{{ post.content|safe }}</div>

</div>

{% endblock %}