old_django_test_tasks/old_django_test_tasks/apps/transfer_money/urls.py
from django.urls import re_path
from . import views

urlpatterns = [
    re_path(r'^$', views.SendMoneyFormView.as_view())
]

old_django_test_tasks/old_django_test_tasks/tests_django/urls.py
from django.conf import settings
from django.urls import include, path
from django.conf.urls import url
from django.contrib import admin
from django.contrib.staticfiles.urls import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^o/', include('oauth2_provider.urls', namespace='oauth2_provider')),
    path('cats/', include('apps.cats.urls')),
    path('cars/', include('apps.cars.urls')),
    # path('image-sizer/', include('apps.image_sizer.urls')),
    path('loans/', include('apps.loans.urls')),
    path('menu-tag/', include('apps.menu_tag.urls')),
    path('playschool/', include('apps.playschool.urls')),
    # path('testing/', include('apps.testing.urls')),
    path('transfer-money/', include('apps.transfer_money.urls')),
    path('generate-keys/', include('apps.gen_keys.urls')),
    path('blog/', include('apps.blog.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls'))
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


if settings.DEBUG:
    urlpatterns += static(
        settings.STATIC_URL, document_root=settings.STATIC_ROOT
    )
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

old_django_test_tasks/old_django_test_tasks/apps/transfer_money/models.py
from django.contrib.auth.models import User
from django.db import models
from django.core.validators import MinValueValidator, MaxValueValidator

from djmoney.models.fields import MoneyField
from djmoney.models.validators import MinMoneyValidator


class Client(models.Model):
    user = models.ForeignKey(
        User, on_delete=models.CASCADE, verbose_name='Пользователь')
    inn = models.IntegerField(
        validators=[MinValueValidator(100), MaxValueValidator(999)],
        verbose_name='ИНН')
    balance = MoneyField(
        max_digits=10,
        decimal_places=2,
        verbose_name='Баланс счёта',
        validators=[MinMoneyValidator(0)])

    class Meta:
        verbose_name = 'Клиент'
        verbose_name_plural = 'Клиенты'

    def __str__(self):
        return '{id} {inn}'.format(id=str(self.id), inn=str(self.inn))

old_django_test_tasks/old_django_test_tasks/apps/transfer_money/forms.py
import string

from django import forms

from djmoney.forms.fields import MoneyField

from .models import Client


class SendMoneyForm(forms.Form):
    donor = forms.ModelChoiceField(
        queryset=Client.objects.all(), label='Отправитель')
    recipients = forms.CharField(widget=forms.Textarea, label='Получатели')
    amount = MoneyField(label='Сумма')

    def clean_recipients(self):
        data = self.cleaned_data['recipients']
        translator = str.maketrans(string.punctuation, ' '*len(string.punctuation))
        inns = data.translate(translator).split()
        clients_inn_list = Client.objects.all().values_list('inn', flat=True)
        errors = []
        non_digit_inns = []
        absent_inns = []
        for inn in inns:
            try:
                int_inn = int(inn)
            except ValueError:
                if inn not in non_digit_inns:
                    non_digit_inns.append(inn)
            else:
                if int_inn not in clients_inn_list:
                    if str(int_inn) not in absent_inns:
                        absent_inns.append(str(int_inn))
        for inn in non_digit_inns:
            errors.append('Инн {} должен состоять только из цифр'.format(inn))
        for inn in absent_inns:
            errors.append('Инн {} отсутствует в базе данных'.format(inn))
        if errors:
            raise forms.ValidationError(errors)
        return data

    def clean_amount(self):
        amount = self.cleaned_data['amount']
        donor = self.cleaned_data['donor']
        if float(amount.amount) < 0.01:
            raise forms.ValidationError('Это поле не может быть меньше 0.01')
        if amount > donor.balance:
            raise forms.ValidationError('Сумма превышает баланс отправителя')
        return amount

old_django_test_tasks/old_django_test_tasks/apps/transfer_money/views.py
# -*- coding: utf-8 -*-
import string

from django.db import transaction
from django.http import JsonResponse
from django.views.generic.edit import FormView

from djmoney.money import Money

from .forms import SendMoneyForm
from .models import Client


class SendMoneyFormView(FormView):
    form_class = SendMoneyForm
    template_name = 'transfer_money/index.html'
    success_url = 'transfer_money/index.html'

    def get(self, request, *args, **kwargs):
        context = self.get_context_data(**kwargs)
        context['clients'] = Client.objects.all()
        return self.render_to_response(context)

    def form_invalid(self, form):
        response = super(SendMoneyFormView, self).form_invalid(form)
        if self.request.is_ajax():
            return JsonResponse(form.errors, status=500)
        else:
            return response

    def form_valid(self, form):
        response = super(SendMoneyFormView, self).form_valid(form)
        if self.request.is_ajax():
            donor = form.cleaned_data['donor']
            recipients_string = form.cleaned_data['recipients']
            translator = str.maketrans(string.punctuation, ' ' * len(string.punctuation))
            recipient_inns = list(map(int, recipients_string.translate(translator).split()))
            recipients = Client.objects.filter(inn__in=recipient_inns)

            with transaction.atomic():
                amount = form.cleaned_data['amount']
                payment_for_each_recipient = amount / recipients.count()
                correct_payment_for_each_recipient = Money(round(float(payment_for_each_recipient) - 0.005, 2), 'RUB')
                actual_payment = Money(
                    round(float(payment_for_each_recipient), 2) * recipients.count(), 'RUB')
                correction_amount = Money(0.01, 'RUB') if actual_payment != amount else Money(0, 'RUB')
                donor.balance += correction_amount
                donor.balance -= amount
                donor.save()
                for recipient in recipients:
                    recipient.balance += correct_payment_for_each_recipient
                    recipient.save()
            clients = list(Client.objects.values())
            data = {'message': 'Форма успешно отправлена',
                    'clients': clients}
            return JsonResponse(data)
        else:
            return response

old_django_test_tasks/old_django_test_tasks/apps/transfer_money/templates/transfer_money/base.html
<!DOCTYPE html>
<html>
    <head>
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/babel-core/6.1.19/browser.min.js"></script>
        <title>
            {% block title %}
            {% endblock title %}
        </title>
    </head>
    <body>
        <header>
        </header>
        <div id="wrapper">
            {% block content %}
                If you see this, something is wrong!
            {% endblock content %}
        </div>
        <div class="footer">
        </div>
    </body>
</html>

old_django_test_tasks/old_django_test_tasks/apps/transfer_money/templates/transfer_money/index.html
{% extends 'transfer_money/base.html' %}
{% block title %}
    Transfer money
{% endblock %}
{% block content %}
<h1>Выполнение перевода >= 1 количеству клиентов</h1>
    <div>
        <form id="form" action="" method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" value="Отправить">
        </form>
    </div>
    <table>
        <th>
            <tr>
                <td>ID</td>
                <td>ИНН</td>
                <td>Баланс</td>
            </tr>
        </th>
        <tbody>
            {% for client in clients %}
                <tr>
                    <td>{{client.id}}</td>
                    <td>{{client.inn}}</td>
                    <td>{{client.balance}}</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>

    <script>

    $(document).ready(function(){

        function handleFormSuccess(data, textStatus, jqXHR){
            $myForm[0].reset(); // сброс данных формы
            $('#recipients_err').remove();
            $('#amount_err').remove();
            $('table').remove();
            var table = '<table><th><tr><td>ID</td><td>ИНН</td><td>Баланс</td></tr></th><tbody>';
            for (let client of data.clients){
                table += `<tr><td>${client.id}</td><td>${client.inn}</td><td>${client.balance} руб.</td></tr>`;
            }
            table += '</tbody><table>';
            $('#form').parent().append(table);
        }

        function handleFormError(jqXHR, textStatus, errorThrown){
            var errors = $.parseJSON(jqXHR.responseText);
            var recipients_errors = '<ul class="errorlist" id="recipients_err">';
            var amount_errors = '<ul class="amount_err errorlist" id="amount_err">';

            for (let category in errors){
                if (category == 'recipients'){
                    for (let error of errors[category]){
                        recipients_errors += `<li>${error}</li>`;
                    }
                } else {
                    amount_errors += `<li>${errors[category]}</li>`;
                }
            }
            recipients_errors += '</ul>';
            amount_errors += '</ul>';
            $('#recipients_err').remove();
            $('#amount_err').remove();
            var recipients_container = $('label[for="id_recipients"]').parent();
            var amount_container = $('label[for="id_amount_0"]').parent();
            $(recipients_container).prepend(recipients_errors);
            $(amount_container).prepend(amount_errors);
        }

        var $myForm = $('#form');
        $myForm.submit(function(event){
            event.preventDefault();
            var $formData = $(this).serialize();
            var $thisURL = $myForm.attr('data-url') || window.location.href // or set your own url
            $.ajax({
                method: "POST",
                url: $thisURL,
                data: $formData,
                success: handleFormSuccess,
                error: handleFormError
            })
        });
    })
    </script>

{% endblock %}