old_django_test_tasks/old_django_test_tasks/apps/blog/urls.py
from django.urls import path

from . import views

app_name = 'blog'


urlpatterns = [
    path('', views.PostList.as_view(), name='home'),
    path('add/', views.PostCreate.as_view(), name='add_post'),
    path('<slug:slug>/', views.PostDetail.as_view(), name='post_detail'),
]

old_django_test_tasks/old_django_test_tasks/tests_django/urls.py
from django.conf import settings
from django.urls import include, path
from django.conf.urls import url
from django.contrib import admin
from django.contrib.staticfiles.urls import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^o/', include('oauth2_provider.urls', namespace='oauth2_provider')),
    path('cats/', include('apps.cats.urls')),
    path('cars/', include('apps.cars.urls')),
    # path('image-sizer/', include('apps.image_sizer.urls')),
    path('loans/', include('apps.loans.urls')),
    path('menu-tag/', include('apps.menu_tag.urls')),
    path('playschool/', include('apps.playschool.urls')),
    # path('testing/', include('apps.testing.urls')),
    path('transfer-money/', include('apps.transfer_money.urls')),
    path('generate-keys/', include('apps.gen_keys.urls')),
    path('blog/', include('apps.blog.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls'))
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


if settings.DEBUG:
    urlpatterns += static(
        settings.STATIC_URL, document_root=settings.STATIC_ROOT
    )
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

old_django_test_tasks/old_django_test_tasks/apps/blog/models.py
from django.db import models
from django.urls import reverse
from slugify import slugify


from ckeditor.fields import RichTextField


class Post(models.Model):
    title = models.CharField(max_length=200, unique=True)
    slug = models.SlugField(max_length=200, unique=True)
    created_on = models.DateTimeField(auto_now_add=True)
    content = RichTextField()
    image = models.ImageField(upload_to=f'blog/images/%Y/%m/%d')

    class Meta:
        ordering = ['-created_on']

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('blog:post_detail', args=[self.slug])

old_django_test_tasks/old_django_test_tasks/apps/blog/forms.py
from django import forms

from ckeditor.widgets import CKEditorWidget

from .models import Post


class PostCreateForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('title', 'content', 'image')
        widgets = {
            'title': forms.TextInput(
                attrs={
                    'class': 'title-field',
                    'placeholder': 'Введите название статьи'
                }
            ),
            'content': CKEditorWidget(attrs={'class': 'content-field'}),
            'image': forms.ClearableFileInput(attrs={'class': 'image-field'}),
        }

old_django_test_tasks/old_django_test_tasks/apps/blog/views.py
from django.views.generic import ListView, DetailView
from django.views.generic.edit import CreateView

from .models import Post
from .forms import PostCreateForm


class PostList(ListView):
    queryset = Post.objects.all().order_by('-created_on')[:10]
    template_name = 'index.html'


class PostDetail(DetailView):
    model = Post
    template_name = 'post_detail.html'


class PostCreate(CreateView):
    model = Post
    form_class = PostCreateForm
    template_name = 'post_create.html'

old_django_test_tasks/old_django_test_tasks/apps/blog/templates/includes/header.html
{% load static %}
<header class="main-header">
    <a href="{% url 'blog:home' %}"><img src="{% static 'blog/assets/Logo_Kodland.png' %}"></a>
    <a href="{% url 'blog:home' %}" class="main-header-blog">Блог</a>
    <a href="{% url 'blog:add_post' %}" class="main-header-add-article">+ Добавить статью</a>
</header>

old_django_test_tasks/old_django_test_tasks/apps/blog/templates/includes/heading-article.html
<div class="heading-article">
  <div class="heading-article-label-new">NEW</div>
  <h2 class="heading-article-header">{{ post_list.0.title }}</h2>
  <div class="heading-article-group">
    <div class="heading-article-perex">
      {{ post_list.0.content|safe|truncatechars:200 }}
    </div>
    <img class="heading-article-img" src="{{ post_list.0.image.url }}">
  </div>
  {% if post_list %}
    <a href="{% url 'blog:post_detail' post_list.0.slug  %}" class="heading-article-read-button">Читать</a>
  {% endif %}
</div>